# Generated by Django 5.1.5 on 2025-02-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, help_text='Your address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='certifications',
            field=models.TextField(blank=True, help_text='List your certifications (e.g., AWS Certified, PMP)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, help_text='Your GitHub profile URL', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='hobbies_interests',
            field=models.TextField(blank=True, help_text='List your hobbies and interests', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(blank=True, help_text='Your current or desired job title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, help_text='List languages you speak (e.g., English, Spanish)', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Your LinkedIn profile URL', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='portfolio',
            field=models.URLField(blank=True, help_text='Your portfolio website URL', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_id',
            field=models.IntegerField(default=1, help_text='The selected template ID'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(help_text='List your educational background'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(help_text='Your email address', max_length=254),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(help_text='Describe your work experience'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(help_text='Your full name', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(help_text='Your phone number', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(help_text='List your skills (e.g., Python, Django, JavaScript)'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(help_text='A brief summary of your professional experience'),
        ),
    ]
