# Generated by Django 5.1.5 on 2025-02-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_remove_resume_education_resume_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='introduction',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='city_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='employer_company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='employer_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='employer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='employer_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='closing',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='greeting',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
